name: mineral_project
description: Build a powerful Discord applications in Dart
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
 mineral: ^2.6.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
